### PR TITLE
fix: use JSON5.parse instead of JSON.parse

### PR DESCRIPTION
**Pull request by axetroy**
Use JSON5, and allow comments in ``tsconfig.json``.

no more throw Error.

Related: #91, #99

### CODE REVIEW

**Comment by capaj** [comment]
I too am seeing this error. 
```
[Extension Host] SyntaxError: Unexpected token / in JSON at position 256
    at JSON.parse (<anonymous>)
    at /home/capaj/.vscode/extensions/christian-kohler.path-intellisense-1.4.2/out/src/utils/config.js:20:25
    at Object.g [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:84:807)
    at Object.enter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:88:85)
    at n.Class.derive._oncancel._run (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:89:932)
    at n.Class.derive._oncancel._completed (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:89:373)
    at e.resolveOk (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:451:201)
    at t._receiveReply (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:608:994)
    at t._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:607:440)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:604:773
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:103:886
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:105:344)
    at a (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:156:881)
    at Socket._socketDataListener (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:157:95)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
log.ts:169   ERR Unexpected token / in JSON at position 256: SyntaxError: Unexpected token / in JSON at position 256
    at JSON.parse (<anonymous>)
    at /home/capaj/.vscode/extensions/christian-kohler.path-intellisense-1.4.2/out/src/utils/config.js:20:25
    at Object.g [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:84:807)
    at Object.enter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:88:85)
    at n.Class.derive._oncancel._run (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:89:932)
    at n.Class.derive._oncancel._completed (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:89:373)
    at e.resolveOk (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:451:201)
    at t._receiveReply (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:608:994)
    at t._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:607:440)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:604:773
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:103:886
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:105:344)
    at a (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:156:881)
    at Socket._socketDataListener (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:157:95)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```
Why hasn't this been merged yet @ChristianKohler ?

**Comment by capaj** [comment]
@axetroy if you want, you can use a fork of mine, where I incorporated your patch: https://github.com/capaj/PathIntellisense

full name of extension is: `capaj.path-intellisense`

**Comment by ChristianKohler** [comment]
Thank you @capaj and sorry for the late response. Had my sabbatical.

**Pull request merged**
