### PR TITLE
feat: added support for NixOS config files

### PR DESCRIPTION
**Pull request by KhanKudo**
This PR resolves the feature request from the official vscode-nix-ide extension repository. (Closes nix-community/vscode-nix-ide#379)
It doesn't change any of the existing behavior, only extends it by adding a new provider for _**/*.nix_ file pattern. This provider has also been placed after the javascript provider to ensure it never overwrites it.
The primary complexity of implementing this feature was the fact that in .nix configs file paths are primarily placed outside of "quotes" resulting in the default vscode context.fromString property being empty, as there is no string to recognize. A custom short regex has been used to match the expected behavior of context.fromString in cases without quotation marks. Worth noting is that, if the path is placed in a string, the default result of context.fromString is forwarded, without invoking any of the custom regex recognition.

### CODE REVIEW

**Comment by ChristianKohler** [comment]
Hi @KhanKudo 

I reviewed and tested your PR. It works as expected and the code is easy to understand. I like how you added it as a separate provider and made sure it doesn't conflict with the existing solution. Thank you for your amazing work 🤩

I noticed that you are reusing the `provide` from the JavaScript provider. It is almost the same code so I see why it would make sense. My idea with the providers and the util functions was, that the common code is in utils and the providers do not depend on each other. This ensures that single providers can be refactored in the future without me having to worry that I break another provider. 

Could you duplicate code? It is a few duplicates line but mostly just calls to utils fns. The file `createCompletionItem.ts` which is currently in the Javascript provider could be moved into the utils folder. It is not 100% provider agnostic but enough to justify to share it. This way, the providers are completely independent from each other. Would that be good?

Note: the test are not running on Ci. This has nothing to do with your change. I have to check what the issue. 

Thank you again for your contribution. Looking forward to merge the first provider next to JS

**Comment by KhanKudo** [comment]
I absolutely agree, different providers should not depend on each other. I have pushed a new commit that moves `createCompletionItem.ts` and `createContext.ts` to the utils folder. And whilst I usually prefer to avoid code duplication at all cost, I definitely have to agree that in this case, it is a lot better to have some duplication but keep independent code separate.
Given that javascript and nix have basically nothing in common, it is certainly a good practice to assume they might have different needs and thus provider differences in the future.

**Comment by ChristianKohler** [comment]
Thank you @KhanKudo for making those changes. Looks very good. 

The only thing you missed is to revert the changes in the javascript provider in the `provide` function. We don't need to export it anymore and have the optional parameter. Could you fix that? After that from my side the Nix support is ready to be published :-)

**Comment by KhanKudo** [comment]
Oh that's a silly oversight haha.
I'll fix it in just a sec ;)

**Comment by ChristianKohler** [comment]
Thank you @KhanKudo for your contribution. Nice work and pleasant discussion. I will create a new release with your PR. 🚀

**Pull request merged**
